executed: '2025-12-25T15:11:53.399Z'
results:
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /teams/{username}/pipelines_config/variables
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 55
        character: 29
      end:
        line: 60
        character: 76
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /teams/{username}/pipelines_config/variables
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 100
        character: 18
      end:
        line: 101
        character: 61
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /teams/{username}/pipelines_config/variables/{variable_uuid}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 177
        character: 29
      end:
        line: 182
        character: 67
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /teams/{username}/pipelines_config/variables/{variable_uuid}
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 186
        character: 29
      end:
        line: 188
        character: 50
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /teams/{username}/pipelines_config/variables/{variable_uuid}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 233
        character: 18
      end:
        line: 234
        character: 60
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /teams/{username}/search/code
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 367
        character: 29
      end:
        line: 372
        character: 57
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /teams/{username}/search/code
      - get
      - responses
      - '400'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 386
        character: 29
      end:
        line: 388
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /teams/{username}/search/code
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 395
        character: 29
      end:
        line: 397
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /teams/{username}/search/code
      - get
      - responses
      - '429'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 401
        character: 29
      end:
        line: 403
        character: 50
