executed: '2025-12-23T22:59:36.505Z'
results:
  - code: openapi-external-docs-error
    message: OpenAPI MUST Have External Documentation
    path: []
    severity: 0
    range:
      start:
        line: 0
        character: 0
      end:
        line: 2791
        character: 13
  - code: openapi-info-license-error
    message: Info MUST Have License
    path:
      - info
    severity: 0
    range:
      start:
        line: 1
        character: 5
      end:
        line: 18
        character: 32
  - code: invalid-ref
    path:
      - paths
      - /addon/linkers
      - get
      - responses
      - '401'
      - content
      - application/json
      - schema
      - $ref
    message: '''#/components/schemas/error'' does not exist'
    severity: 0
    range:
      start:
        line: 38
        character: 22
      end:
        line: 38
        character: 50
  - code: openapi-components-examples-error
    message: Components MUST Have a Examples Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2790
        character: 11
      end:
        line: 2791
        character: 13
  - code: openapi-components-headers-error
    message: Components MUST Have a Headers Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2790
        character: 11
      end:
        line: 2791
        character: 13
  - code: openapi-components-parameters-error
    message: Components MUST Have a Parameters Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2790
        character: 11
      end:
        line: 2791
        character: 13
  - code: openapi-security-schemes-error
    message: Components MUST Have a Security Schemes
    path:
      - components
    severity: 0
    range:
      start:
        line: 2790
        character: 11
      end:
        line: 2791
        character: 13
