executed: '2025-12-25T22:21:26.335Z'
results:
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /workspaces/{workspace}/pipelines-config/variables
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 908
        character: 18
      end:
        line: 909
        character: 61
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /workspaces/{workspace}/pipelines-config/variables/{variable_uuid}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1051
        character: 18
      end:
        line: 1052
        character: 60
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /workspaces/{workspace}/projects
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1238
        character: 18
      end:
        line: 1239
        character: 50
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /workspaces/{workspace}/projects/{project_key}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1448
        character: 18
      end:
        line: 1449
        character: 50
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation Identifier MUST Be camelCase
    path:
      - paths
      - >-
        /workspaces/{workspace}/projects/{project_key}/default-reviewers/{selected_user}
      - delete
      - operationId
    severity: 0
    range:
      start:
        line: 1849
        character: 19
      end:
        line: 1849
        character: 71
  - code: invalid-ref
    path:
      - paths
      - >-
        /workspaces/{workspace}/projects/{project_key}/permissions-config/groups/{group_slug}
      - put
      - requestBody
      - $ref
    message: >-
      '#/components/requestBodies/bitbucket.apps.permissions.serializers.ProjectPermissionUpdateSchema'
      does not exist
    severity: 0
    range:
      start:
        line: 2544
        character: 14
      end:
        line: 2545
        character: 105
