executed: '2025-12-23T23:31:02.595Z'
results:
  - code: invalid-ref
    path:
      - paths
      - /hook_events/{subject_type}
      - get
      - responses
      - '404'
      - content
      - application/json
      - schema
      - $ref
    message: '''#/components/schemas/error'' does not exist'
    severity: 0
    range:
      start:
        line: 81
        character: 22
      end:
        line: 81
        character: 50
  - code: openapi-components-examples-error
    message: Components MUST Have a Examples Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2529
        character: 11
      end:
        line: 2584
        character: 20
  - code: openapi-components-headers-error
    message: Components MUST Have a Headers Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2529
        character: 11
      end:
        line: 2584
        character: 20
  - code: openapi-components-parameters-error
    message: Components MUST Have a Parameters Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2529
        character: 11
      end:
        line: 2584
        character: 20
  - code: invalid-ref
    path:
      - components
      - schemas
      - paginated_hook_events
      - properties
      - values
      - items
      - $ref
    message: '''#/components/schemas/hook_event'' does not exist'
    severity: 0
    range:
      start:
        line: 2576
        character: 18
      end:
        line: 2576
        character: 51
