executed: '2025-12-26T12:43:26.262Z'
results:
  - code: openapi-tags-one-error
    message: MUST Be At Least One Tag
    path:
      - tags
    severity: 0
    range:
      start:
        line: 22
        character: 5
      end:
        line: 22
        character: 8
  - code: openapi-components-headers-error
    message: Components MUST Have a Headers Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 187
        character: 11
      end:
        line: 195
        character: 17
  - code: openapi-components-parameters-error
    message: Components MUST Have a Parameters Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 187
        character: 11
      end:
        line: 195
        character: 17
  - code: openapi-security-schemes-error
    message: Components MUST Have a Security Schemes
    path:
      - components
    severity: 0
    range:
      start:
        line: 187
        character: 11
      end:
        line: 195
        character: 17
