executed: '2025-12-25T18:39:12.829Z'
results:
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/permissions-config/users
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 44
        character: 29
      end:
        line: 49
        character: 85
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/permissions-config/users
      - get
      - responses
      - '401'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 53
        character: 29
      end:
        line: 55
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/permissions-config/users
      - get
      - responses
      - '403'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 59
        character: 29
      end:
        line: 61
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/permissions-config/users
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 65
        character: 29
      end:
        line: 67
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 184
        character: 29
      end:
        line: 189
        character: 74
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '401'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 193
        character: 29
      end:
        line: 195
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '403'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 199
        character: 29
      end:
        line: 201
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 207
        character: 29
      end:
        line: 209
        character: 50
  - code: invalid-ref
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}
      - put
      - requestBody
      - $ref
    message: >-
      '#/components/requestBodies/bitbucket.apps.permissions.serializers.RepoPermissionUpdateSchema'
      does not exist
    severity: 0
    range:
      start:
        line: 297
        character: 14
      end:
        line: 298
        character: 102
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /user
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 361
        character: 29
      end:
        line: 366
        character: 55
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /user
      - get
      - responses
      - '401'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 370
        character: 29
      end:
        line: 372
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /user/emails
      - get
      - responses
      - default
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 410
        character: 29
      end:
        line: 412
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /user/emails/{email}
      - get
      - responses
      - default
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 451
        character: 29
      end:
        line: 453
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /user/permissions/repositories
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 497
        character: 29
      end:
        line: 502
        character: 80
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /user/permissions/workspaces
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 560
        character: 29
      end:
        line: 565
        character: 79
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /user/permissions/workspaces
      - get
      - responses
      - '401'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 569
        character: 29
      end:
        line: 571
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 631
        character: 29
      end:
        line: 636
        character: 57
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 642
        character: 29
      end:
        line: 644
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/pipelines_config/variables
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 698
        character: 29
      end:
        line: 703
        character: 76
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /users/{selected_user}/pipelines_config/variables
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 743
        character: 18
      end:
        line: 744
        character: 61
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/pipelines_config/variables/{variable_uuid}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 821
        character: 29
      end:
        line: 826
        character: 67
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/pipelines_config/variables/{variable_uuid}
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 830
        character: 29
      end:
        line: 832
        character: 50
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /users/{selected_user}/pipelines_config/variables/{variable_uuid}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 877
        character: 18
      end:
        line: 878
        character: 60
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /users/{selected_user}/properties/{app_key}/{property_name}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 998
        character: 18
      end:
        line: 999
        character: 63
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/properties/{app_key}/{property_name}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1070
        character: 29
      end:
        line: 1075
        character: 68
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/search/code
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1184
        character: 29
      end:
        line: 1189
        character: 59
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/search/code
      - get
      - responses
      - '400'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1203
        character: 29
      end:
        line: 1205
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/search/code
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1212
        character: 29
      end:
        line: 1214
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/search/code
      - get
      - responses
      - '429'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1218
        character: 29
      end:
        line: 1220
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/ssh-keys
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1252
        character: 29
      end:
        line: 1289
        character: 70
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/ssh-keys
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1295
        character: 29
      end:
        line: 1297
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/ssh-keys/{key_id}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1454
        character: 29
      end:
        line: 1459
        character: 65
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /users/{selected_user}/ssh-keys/{key_id}
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1465
        character: 29
      end:
        line: 1467
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /workspaces/{workspace}/projects/{project_key}/permissions-config/users
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1586
        character: 29
      end:
        line: 1591
        character: 82
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /workspaces/{workspace}/projects/{project_key}/permissions-config/users
      - get
      - responses
      - '401'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1595
        character: 29
      end:
        line: 1597
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /workspaces/{workspace}/projects/{project_key}/permissions-config/users
      - get
      - responses
      - '403'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1601
        character: 29
      end:
        line: 1603
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - /workspaces/{workspace}/projects/{project_key}/permissions-config/users
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1609
        character: 29
      end:
        line: 1611
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1729
        character: 29
      end:
        line: 1734
        character: 71
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '401'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1738
        character: 29
      end:
        line: 1740
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '403'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1744
        character: 29
      end:
        line: 1746
        character: 50
  - code: openapi-response-schemas-error
    message: Response MUST Have Schemas
    path:
      - paths
      - >-
        /workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}
      - get
      - responses
      - '404'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1753
        character: 29
      end:
        line: 1755
        character: 50
  - code: invalid-ref
    path:
      - paths
      - >-
        /workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}
      - put
      - requestBody
      - $ref
    message: >-
      '#/components/requestBodies/bitbucket.apps.permissions.serializers.ProjectPermissionUpdateSchema'
      does not exist
    severity: 0
    range:
      start:
        line: 1843
        character: 14
      end:
        line: 1844
        character: 105
  - code: openapi-tags-one-error
    message: MUST Be At Least One Tag
    path:
      - tags
    severity: 0
    range:
      start:
        line: 1884
        character: 5
      end:
        line: 1884
        character: 8
