executed: '2025-12-27T13:51:37.094Z'
results:
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/archive
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 44
        character: 27
      end:
        line: 58
        character: 73
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/blueprint/instance/{draftId}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 155
        character: 27
      end:
        line: 157
        character: 64
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/blueprint/instance/{draftId}
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 238
        character: 27
      end:
        line: 240
        character: 64
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/search
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 347
        character: 29
      end:
        line: 349
        character: 57
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 477
        character: 29
      end:
        line: 479
        character: 52
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 579
        character: 27
      end:
        line: 581
        character: 56
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 877
        character: 29
      end:
        line: 879
        character: 60
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child/attachment
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1079
        character: 29
      end:
        line: 1081
        character: 57
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child/attachment
      - put
      - requestBody
      - content
      - multipart/form-data
    severity: 0
    range:
      start:
        line: 1154
        character: 30
      end:
        line: 1189
        character: 32
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child/attachment
      - post
      - requestBody
      - content
      - multipart/form-data
    severity: 0
    range:
      start:
        line: 1276
        character: 30
      end:
        line: 1311
        character: 32
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child/attachment/{attachmentId}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1405
        character: 27
      end:
        line: 1407
        character: 73
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child/attachment/{attachmentId}/data
      - post
      - requestBody
      - content
      - multipart/form-data
    severity: 0
    range:
      start:
        line: 1501
        character: 30
      end:
        line: 1536
        character: 32
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child/comment
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1737
        character: 29
      end:
        line: 1739
        character: 57
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/child/{type}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1835
        character: 29
      end:
        line: 1837
        character: 57
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/descendant
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1927
        character: 29
      end:
        line: 1929
        character: 60
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/descendant/{type}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2030
        character: 29
      end:
        line: 2032
        character: 57
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/history
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2135
        character: 29
      end:
        line: 2137
        character: 59
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/history/{version}/macro/id/{macroId}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2230
        character: 29
      end:
        line: 2232
        character: 58
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - >-
        /wiki/rest/api/content/{id}/history/{version}/macro/id/{macroId}/convert/{to}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2370
        character: 29
      end:
        line: 2372
        character: 56
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - >-
        /wiki/rest/api/content/{id}/history/{version}/macro/id/{macroId}/convert/async/{to}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2547
        character: 29
      end:
        line: 2549
        character: 52
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/label
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2664
        character: 29
      end:
        line: 2666
        character: 55
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/label
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2730
        character: 27
      end:
        line: 2734
        character: 58
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/notification/child-created
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 2975
        character: 29
      end:
        line: 2977
        character: 55
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/notification/created
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3053
        character: 29
      end:
        line: 3055
        character: 60
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/pagehierarchy/copy
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3111
        character: 27
      end:
        line: 3113
        character: 67
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/copy
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3190
        character: 27
      end:
        line: 3192
        character: 58
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/permission/check
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3280
        character: 27
      end:
        line: 3282
        character: 67
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/property
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3411
        character: 29
      end:
        line: 3413
        character: 65
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/property
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3471
        character: 27
      end:
        line: 3473
        character: 64
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/property/{key}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3621
        character: 29
      end:
        line: 3623
        character: 60
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/property/{key}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3689
        character: 27
      end:
        line: 3691
        character: 64
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/property/{key}
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3790
        character: 27
      end:
        line: 3792
        character: 69
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/restriction
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 3999
        character: 29
      end:
        line: 4001
        character: 68
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/restriction
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 4093
        character: 27
      end:
        line: 4095
        character: 77
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/restriction
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 4200
        character: 27
      end:
        line: 4202
        character: 77
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/restriction/byOperation
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 4403
        character: 29
      end:
        line: 4411
        character: 63
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/restriction/byOperation/{operationKey}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 4528
        character: 29
      end:
        line: 4530
        character: 63
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/state
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 5339
        character: 29
      end:
        line: 5341
        character: 65
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/state
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 5400
        character: 27
      end:
        line: 5402
        character: 64
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/state/available
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 5571
        character: 29
      end:
        line: 5573
        character: 67
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/version
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 5673
        character: 29
      end:
        line: 5675
        character: 57
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/version
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 5752
        character: 27
      end:
        line: 5754
        character: 57
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /wiki/rest/api/content/{id}/version/{versionNumber}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 5855
        character: 29
      end:
        line: 5857
        character: 52
