executed: '2025-12-23T22:06:32.654Z'
results:
  - code: openapi-external-docs-error
    message: OpenAPI MUST Have External Documentation
    path: []
    severity: 0
    range:
      start:
        line: 0
        character: 0
      end:
        line: 2748
        character: 13
  - code: openapi-info-license-error
    message: Info MUST Have License
    path:
      - info
    severity: 0
    range:
      start:
        line: 1
        character: 5
      end:
        line: 9
        character: 32
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers
      - get
    severity: 0
    range:
      start:
        line: 12
        character: 8
      end:
        line: 31
        character: 21
  - code: invalid-ref
    path:
      - paths
      - /addon/linkers
      - get
      - responses
      - '401'
      - content
      - application/json
      - schema
      - $ref
    message: '''#/components/schemas/error'' does not exist'
    severity: 0
    range:
      start:
        line: 27
        character: 22
      end:
        line: 27
        character: 50
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers/{linker_key}
      - get
    severity: 0
    range:
      start:
        line: 34
        character: 8
      end:
        line: 61
        character: 21
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers/{linker_key}/values
      - delete
    severity: 0
    range:
      start:
        line: 72
        character: 11
      end:
        line: 97
        character: 21
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers/{linker_key}/values
      - get
    severity: 0
    range:
      start:
        line: 98
        character: 8
      end:
        line: 140
        character: 21
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers/{linker_key}/values
      - post
    severity: 0
    range:
      start:
        line: 141
        character: 9
      end:
        line: 189
        character: 21
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers/{linker_key}/values
      - put
    severity: 0
    range:
      start:
        line: 190
        character: 8
      end:
        line: 238
        character: 21
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers/{linker_key}/values/{value_id}
      - delete
    severity: 0
    range:
      start:
        line: 249
        character: 11
      end:
        line: 274
        character: 21
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /addon/linkers/{linker_key}/values/{value_id}
      - get
    severity: 0
    range:
      start:
        line: 275
        character: 8
      end:
        line: 300
        character: 21
  - code: openapi-tags-one-error
    message: MUST Be At Least One Tag
    path:
      - tags
    severity: 0
    range:
      start:
        line: 316
        character: 5
      end:
        line: 316
        character: 8
  - code: openapi-components-examples-error
    message: Components MUST Have a Examples Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2747
        character: 11
      end:
        line: 2748
        character: 13
  - code: openapi-components-headers-error
    message: Components MUST Have a Headers Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2747
        character: 11
      end:
        line: 2748
        character: 13
  - code: openapi-components-parameters-error
    message: Components MUST Have a Parameters Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 2747
        character: 11
      end:
        line: 2748
        character: 13
  - code: openapi-security-schemes-error
    message: Components MUST Have a Security Schemes
    path:
      - components
    severity: 0
    range:
      start:
        line: 2747
        character: 11
      end:
        line: 2748
        character: 13
