executed: '2025-12-24T23:28:48.706Z'
results:
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/branch-restrictions
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 454
        character: 29
      end:
        line: 456
        character: 73
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/commit/{commit}/properties/{app_key}/{property_name}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 1599
        character: 18
      end:
        line: 1600
        character: 63
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation Identifier MUST Be camelCase
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/commits/{revision}
      - post
      - operationId
    severity: 0
    range:
      start:
        line: 3044
        character: 19
      end:
        line: 3044
        character: 61
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation Identifier MUST Be camelCase
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/effective-branching-model
      - get
      - operationId
    severity: 0
    range:
      start:
        line: 4695
        character: 19
      end:
        line: 4695
        character: 81
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/permissions-config/groups/{group_slug}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 8063
        character: 18
      end:
        line: 8065
        character: 98
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 8370
        character: 18
      end:
        line: 8372
        character: 98
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/properties/{app_key}/{property_name}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 11088
        character: 18
      end:
        line: 11089
        character: 63
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/pullrequests
      - post
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 11339
        character: 27
      end:
        line: 11341
        character: 54
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 11552
        character: 27
      end:
        line: 11554
        character: 54
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/pullrequests/{pullrequest_id}/properties/{app_key}/{property_name}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 13524
        character: 18
      end:
        line: 13525
        character: 63
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/refs/tags
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 14186
        character: 29
      end:
        line: 14188
        character: 59
