executed: '2025-12-26T12:56:16.308Z'
results:
  - code: invalid-ref
    path:
      - paths
      - /atlassian-connect/1/app/module/dynamic
      - get
      - responses
      - '200'
      - content
      - '*/*'
      - schema
      - $ref
    message: '''#/components/schemas/ConnectModules'' does not exist'
    severity: 0
    range:
      start:
        line: 51
        character: 22
      end:
        line: 51
        character: 59
  - code: invalid-ref
    path:
      - paths
      - /atlassian-connect/1/app/module/dynamic
      - get
      - responses
      - '401'
      - content
      - '*/*'
      - schema
      - $ref
    message: '''#/components/schemas/DynamicModulesErrorMessage'' does not exist'
    severity: 0
    range:
      start:
        line: 57
        character: 22
      end:
        line: 57
        character: 71
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /atlassian-connect/1/app/module/dynamic
      - post
      - requestBody
      - content
      - '*/*'
    severity: 0
    range:
      start:
        line: 93
        character: 16
      end:
        line: 95
        character: 57
  - code: openapi-components-examples-error
    message: Components MUST Have a Examples Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 206
        character: 11
      end:
        line: 212
        character: 20
  - code: openapi-components-headers-error
    message: Components MUST Have a Headers Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 206
        character: 11
      end:
        line: 212
        character: 20
  - code: openapi-components-parameters-error
    message: Components MUST Have a Parameters Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 206
        character: 11
      end:
        line: 212
        character: 20
