executed: '2025-12-26T12:45:35.387Z'
results:
  - code: openapi-tags-one-error
    message: MUST Be At Least One Tag
    path:
      - tags
    severity: 0
    range:
      start:
        line: 21
        character: 5
      end:
        line: 21
        character: 8
  - code: openapi-components-headers-error
    message: Components MUST Have a Headers Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 350
        character: 11
      end:
        line: 418
        character: 17
  - code: openapi-components-parameters-error
    message: Components MUST Have a Parameters Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 350
        character: 11
      end:
        line: 418
        character: 17
  - code: openapi-security-schemes-error
    message: Components MUST Have a Security Schemes
    path:
      - components
    severity: 0
    range:
      start:
        line: 350
        character: 11
      end:
        line: 418
        character: 17
  - code: invalid-ref
    path:
      - components
      - schemas
      - AuditRecordArray
      - properties
      - _links
      - $ref
    message: '''#/components/schemas/GenericLinks'' does not exist'
    severity: 0
    range:
      start:
        line: 402
        character: 16
      end:
        line: 402
        character: 51
