executed: '2025-12-26T12:46:11.737Z'
results:
  - code: openapi-components-headers-error
    message: Components MUST Have a Headers Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 351
        character: 11
      end:
        line: 424
        character: 20
  - code: openapi-components-parameters-error
    message: Components MUST Have a Parameters Property
    path:
      - components
    severity: 0
    range:
      start:
        line: 351
        character: 11
      end:
        line: 424
        character: 20
  - code: invalid-ref
    path:
      - components
      - schemas
      - AuditRecordArray
      - properties
      - _links
      - $ref
    message: '''#/components/schemas/GenericLinks'' does not exist'
    severity: 0
    range:
      start:
        line: 403
        character: 16
      end:
        line: 403
        character: 51
