executed: '2025-12-24T13:12:10.587Z'
results:
  - code: invalid-ref
    path:
      - paths
      - /pullrequests/{selected_user}
      - get
      - responses
      - '404'
      - content
      - application/json
      - schema
      - $ref
    message: '''#/components/schemas/error'' does not exist'
    severity: 0
    range:
      start:
        line: 51
        character: 22
      end:
        line: 51
        character: 50
  - code: openapi-response-examples-error
    message: Response MUST Have Examples
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 323
        character: 29
      end:
        line: 325
        character: 56
  - code: openapi-request-body-have-examples-error
    message: Request Bodies MUST Have Examples
    path:
      - paths
      - /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}
      - put
      - requestBody
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 393
        character: 27
      end:
        line: 395
        character: 54
  - code: invalid-ref
    path:
      - paths
      - >-
        /repositories/{workspace}/{repo_slug}/pullrequests/{pullrequest_id}/properties/{app_key}/{property_name}
      - put
      - requestBody
      - $ref
    message: '''#/components/requestBodies/application_property'' does not exist'
    severity: 0
    range:
      start:
        line: 2274
        character: 14
      end:
        line: 2274
        character: 63
  - code: invalid-ref
    path:
      - components
      - schemas
      - pullrequest
      - allOf
      - '0'
      - $ref
    message: '''#/components/schemas/object'' does not exist'
    severity: 0
    range:
      start:
        line: 4898
        character: 16
      end:
        line: 4898
        character: 45
  - code: invalid-ref
    path:
      - components
      - schemas
      - pullrequest
      - allOf
      - '1'
      - properties
      - source
      - $ref
    message: '''#/components/schemas/pullrequest_endpoint'' does not exist'
    severity: 0
    range:
      start:
        line: 5120
        character: 20
      end:
        line: 5120
        character: 63
  - code: invalid-ref
    path:
      - components
      - schemas
      - A_pullrequest_comment_task
      - allOf
      - '0'
      - $ref
    message: '''#/components/schemas/A_pull_request_task'' does not exist'
    severity: 0
    range:
      start:
        line: 5448
        character: 16
      end:
        line: 5448
        character: 58
  - code: invalid-ref
    path:
      - components
      - schemas
      - account
      - allOf
      - '1'
      - properties
      - links
      - $ref
    message: '''#/components/schemas/account_links'' does not exist'
    severity: 0
    range:
      start:
        line: 5508
        character: 20
      end:
        line: 5508
        character: 56
